# Generated by Django 2.2.28 on 2023-03-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_auto_20230314_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
