# Generated by Django 2.2.28 on 2023-03-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_auto_20230323_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='views',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
