# Generated by Django 2.2.28 on 2023-03-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0010_auto_20230323_1159'),
        ('ride', '0010_auto_20230323_1145'),
    ]

    operations = [
    ]
